//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.OrderMenu = new HashSet<OrderMenu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsDishes { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Calories { get; set; }
        public Nullable<int> Gram { get; set; }
        public Nullable<int> Protein { get; set; }
        public Nullable<int> Fat { get; set; }
        public Nullable<int> Carb { get; set; }
        public Nullable<int> Mililiters { get; set; }
        public int IDCategory { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenu> OrderMenu { get; set; }
    }
}
