//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenu
    {
        public int ID { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public int IDMenu { get; set; }
        public int Qty { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
